repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.2
    hooks:
      - id: golangci-lint
        args: [--config=.golangci.yml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
