repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.2
    hooks:
      - id: golangci-lint
        args:
        - --config=.golangci.yml
        - ./cmd/...
        - ./config/...
        - ./internal/...

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
    - id: go-tidy
      name: Run go mod tidy
      entry: go mod tidy
      language: system
      pass_filenames: false

    - id: go-test
      name: Run unit tests
      entry: go test -v ./cmd/... ./config/... ./internal/... -count=1
      language: system
      pass_filenames: false

    - id: go-build
      name: Run build
      entry: go build -o bin/gotasker-pro ./cmd/api
      language: system
      pass_filenames: false

    - id: go-vet
      name: Run go vet with correct path
      entry: go vet ./cmd/... ./config/... ./internal/...
      language: system
      pass_filenames: false

    - id: generate-mocks
      name: Generate gomock files
      entry: make mocks
      language: system
